server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/receiptdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baselineOnMigrate: true

cache:
  cache-names: LRU
  capacity: 100